* About
Pegasus Skyscraper is a game scraper and metadata generator for the Pegasus-frontend.

[[https://github.com/mmatyas/pegasus-frontend][Pegasus-frontend]] + [[https://github.com/muldjord/skyscraper][Skyscraper]] = Pegasus Skyscraper

Screenscraper is used as the default scraper.
* Dependencies
+ =skyscraper-git= [[https://aur.archlinux.org/packages/skyscraper-git][AUR]] / [[https://github.com/muldjord/skyscraper][github]]
+ =pegasus-frontend-git= [[https://aur.archlinux.org/packages/pegasus-frontend-git][AUR]] / [[https://github.com/mmatyas/pegasus-frontend][github]]
+ =wget=
  - Debian
    #+BEGIN_SRC bash
    sudo apt install wget
    #+END_SRC
  - Arch
    #+BEGIN_SRC bash
    sudo pacman -S wget
    #+END_SRC
* Installation
you can download the executable using =wget=.

#+BEGIN_SRC bash
wget https://raw.githubusercontent.com/AfzGit/pegasus-skyscraper/main/pgsk && chmod a+x pgsk && sudo mv pgsk /usr/bin/
#+END_SRC

Note: After using the above command, pgsk is stored =/usr/bin=.

Alternatively, download the executable from the [[https://github.com/AfzGit/pegasus-skyscraper/releases/tag/Latest][Releases]] page.
* Usage
=pgsk [DIRECTORY] [CONSOLE]=

[DIRECTORY] = Location of the console games folder

[CONSOLE] = name of the console (always lowercase)

The media folder and the metadata file are both stored in [DIRECTORY]. Add the metadata file in pegasus-frontend for media and games to be detected.
* Examples
- Example 1:
  Fetching media for a GBA game:

  #+BEGIN_SRC bash
  pgsk ~/Games/GBA/ gba
  #+END_SRC

  stores media and metadata in "~/Games/GBA/"
- Example 2:
  Fetching media for a WII game:

  #+BEGIN_SRC bash
  pgsk ~/Games/WII/ wii
  #+END_SRC

  stores media and metadata in "~/Games/WII/"
