* About
Pegasus Skyscraper is a game scraper and metadata generator for the Pegasus-frontend.

[[https://github.com/mmatyas/pegasus-frontend][Pegasus-frontend]] + [[https://github.com/muldjord/skyscraper][Skyscraper]] = Pegasus Scraper

Screenscraper is used as the default scraper.
The media folder and the metadata file are both stored [DIRECTORY]

* Dependencies
+ =Skyscraper v3.7.7+= AUR / [[https://github.com/muldjord/skyscraper][github]]
  - AUR (using yay)
    - =yay -S skyscraper-git=
+ =pegasus-frontend-git= AUR / [[https://github.com/mmatyas/pegasus-frontend][github]]
  - AUR (using yay)
    - =yay -S pegasus-frontend-git=
+ =wget=
  - Debian
    - =sudo apt install wget=
  - Arch
    - =sudo pacman -S wget=
* Installation
you can download the executable using =wget=.

#+BEGIN_SRC bash
wget https://raw.githubusercontent.com/AfzGit/pegasus-skyscraper/main/pgsk && chmod a+x pgsk && sudo mv pgsk /usr/bin/
#+END_SRC

Note: pgsk is stored in your /usr/bin folder.
* Usage
=pgsk [DIRECTORY] [CONSOLE]=

[DIRECTORY] = Location of the console games folder

[CONSOLE] = name of the console
* Examples
- Example 1:
  Fetching media for a GBA game:

  =pgsk ~/Games/GBA/ gba=

  stores media and metadata in '~/Games/GBA/'
- Example 2:
  Fetching media for a WII game:

  =pgsk ~/Games/WII/ wii=

  stores media and metadata in '~/Games/WII/'

then add the metadata file in pegasus-frontend for media and games to be detected.
